CREATE TABLE IF NOT EXISTS friend (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(10) NOT NULL,
    age INT(11) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    hobby VARCHAR(255) NOT NULL,
    remark VARCHAR(255) NOT NULL,
    status INT(11) DEFAULT 1,
    create_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);